Somehow I got a bogon in userinfo.db, and that killed it:

    012-04-05T17:09:03Z <= ((prefix #"dyoo!8a10a006@gateway/web/freenode/ip.138.16.160.6") (command #"JOIN") (params (param #"#racket")))
    userinfo.db/d/dyoo::257: read: expected a closing '"'

     === context ===
    /mnt/rudybot/userinfo.rkt:43:0: info-ref
    /mnt/rudybot/userinfo.rkt:95:2: add!
    /mnt/rudybot/loop.rkt:62:6: do-one-line

Obviously we should swallow exceptions when reading those things.
